module.exports = {
  apps: [
    {
      name: "stackrun-api",
      cwd: "/root/nidus/apps/api",
      script: "/root/nidus/apps/api/stackrun-api",
      interpreter: "none",
      env: {
        DATABASE_URL: "postgresql://nidus:nidus_dev_2026@localhost:5432/nidus",
        REDIS_URL: "redis://:nidus_53abf19648886baa@localhost:6379/0",
        API_PORT: "3001",
        NODE_ENV: "production",
        JWT_SECRET: "stackrun_prod_jwt_secret_2026",
        DASHBOARD_TOKEN: "nimbus-ssr-secret-2026",
        CORS_ORIGINS: "http://2.24.204.31:3000,http://localhost:3000",
        STACKRUN_HOST: "2.24.204.31",
        STACKRUN_DEPLOYS_DIR: "/root/nidus/deploys",
        CADDY_ADMIN_URL: "http://localhost:2019",
        GITHUB_CLIENT_ID: "",
        GITHUB_CLIENT_SECRET: "",
        RESEND_API_KEY: "",
        EMAIL_FROM: "stackrun@stackrun.vercel.app",
        EMAIL_FROM_NAME: "StackRun",
      },
    },
    {
      name: "stackrun-worker",
      cwd: "/root/nidus/workers/deploy",
      script: "/root/nidus/workers/deploy/stackrun-deploy-worker",
      interpreter: "none",
      env: {
        DATABASE_URL: "postgresql://nidus:nidus_dev_2026@localhost:5432/nidus",
        REDIS_URL: "redis://:nidus_53abf19648886baa@localhost:6379/0",
        DOCKER_HOST: "unix:///var/run/docker.sock",
        STACKRUN_HOST: "2.24.204.31",
        STACKRUN_DEPLOYS_DIR: "/root/nidus/deploys",
        WORKER_PORT: "8081",
        WORKER_CONCURRENCY: "4",
        RESEND_API_KEY: "",
        EMAIL_FROM: "stackrun@stackrun.vercel.app",
        EMAIL_FROM_NAME: "StackRun",
      },
    },
    {
      name: "stackrun-dashboard",
      cwd: "/root/nidus/apps/dashboard",
      script: "npm",
      args: "run start",
      env: {
        PORT: "3000",
        NEXT_PUBLIC_API_URL: "http://2.24.204.31:3001",
        DASHBOARD_TOKEN: "nimbus-ssr-secret-2026",
        DASHBOARD_TOKEN: "nimbus-ssr-secret-2026",
      },
    },
    {
      name: "stackrun-docs",
      cwd: "/root/nidus/docs-site",
      script: "npm",
      args: "run start",
      env: {
        PORT: "3002",
      },
    },
  ],
}
