#!/bin/bash
echo "=== Memory Usage Comparison ==="
echo "Binary sizes:"
echo "  Rust proxy:  $(ls -lh /root/stackrun/rust/target/release/stackrun-proxy | awk '{print $5}')"
echo "  Go proxy:    $(ls -lh /root/stackrun/apps/proxy/stackrun-proxy 2>/dev/null | awk '{print $5}')"  
echo "  Caddy:       $(ls -lh /usr/bin/caddy | awk '{print $5}')"
echo "  Go API:      $(ls -lh /root/stackrun/apps/api/stackrun-api | awk '{print $5}')"
echo "  Node (next): $(pm2 show stackrun-dashboard 2>/dev/null | grep memory | tail -1 | awk '{print $4}')"
echo "  Rust CLI:    $(ls -lh /root/stackrun/rust/target/release/nidus | awk '{print $5}')"
echo "  Node CLI:    $(du -sh /root/stackrun/cli/node_modules 2>/dev/null | awk '{print $1}')"
