#!/bin/bash
echo "=== Memory Usage Comparison ==="
echo "Binary sizes:"
echo "  Rust proxy:  $(ls -lh /root/nidus/rust/target/release/nidus-proxy | awk '{print $5}')"
echo "  Go proxy:    $(ls -lh /root/nidus/apps/proxy/nidus-proxy 2>/dev/null | awk '{print $5}')"  
echo "  Caddy:       $(ls -lh /usr/bin/caddy | awk '{print $5}')"
echo "  Go API:      $(ls -lh /root/nidus/apps/api/nidus-api | awk '{print $5}')"
echo "  Node (next): $(pm2 show nidus-dashboard 2>/dev/null | grep memory | tail -1 | awk '{print $4}')"
echo "  Rust CLI:    $(ls -lh /root/nidus/rust/target/release/nidus | awk '{print $5}')"
echo "  Node CLI:    $(du -sh /root/nidus/cli/node_modules 2>/dev/null | awk '{print $1}')"
